# Generated by Django 5.2.4 on 2025-08-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='ordem',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
