# Generated by Django 5.2.4 on 2025-09-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarefa_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nome',
            field=models.TextField(),
        ),
    ]
